[project]
name = "python-template"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]
requires-python = ">=3.11"
dependencies = [
    "asyncio>=3.4.3",
    "flask>=3.1.1",
    "playwright>=1.52.0",
    "python-dotenv>=1.1.0",
    "python-telegram-bot>=22.1",
]
