services:
  - type: web
    name: RedmineBrowser
    env: python
    plan: free
    buildCommand: |
      pip install -r requirements.txt
      python -m playwright install
    startCommand: python main.py
    build:
      # these are the Ubuntu packages matching the missing .so files
      aptPackages:
        - libnss3
        - libxss1
        - libasound2
        - libatk-bridge2.0-0
        - libgtk-4-1
        - libgraphene-1.0-0
        - libgstgl-1.0-0
        - libgstcodecparsers-1.0-0
        - libavif15
        - libenchant-2-2
        - libsecret-1-0
        - libmanette-0.2-0
        - libgles2
        # plus any others you see in the “Missing libraries” error
